# Generated by Django 3.2 on 2023-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edmsapp', '0012_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
