# Generated by Django 3.2 on 2023-06-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edmsapp', '0013_order_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
