# Generated by Django 3.2 on 2023-06-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edmsapp', '0014_alter_order_invoice_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
