# Generated by Django 3.2 on 2023-06-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edmsapp', '0016_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
