# Generated by Django 3.2 on 2023-06-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edmsapp', '0017_delete_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default='', max_length=8),
        ),
    ]
